changelog:
  exclude:
    labels:
      - documentation
      - duplicate
      - invalid
      - wontfix
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - feature
    - title: Fixes 🐛
      labels:
        - bug
    - title: Maintenance
      labels:
        - dependencies
        - .NET
      exclude:
        authors:
          - dependabot
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
        authors:
          - dependabot