name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    defaults:
      run:
        working-directory: Documentation
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true

      - name: build documentation
        run: |
          docfx build --warningsAsErrors

      - name: Building
        run: dotnet build

  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: build_job
    env:
      DATAMINER_DEPLOY_KEY: ${{ secrets.DATAMINER_DEPLOY_KEY }}
    if: ${{ env.DATAMINER_DEPLOY_KEY != '' }}
    defaults:
      run:
        working-directory: Documentation

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Install .NET Tools
        run: |
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.DataMinerDeploy

      - name: Build Documentation project
        run: dotnet build

      - name: Upload package to Catalog
        id: uploadSkyline
        run: |
          ARTIFACT=$(find bin/Debug -name "*.dmapp" | head -n 1)
          echo "id=$(dataminer-catalog-upload --path-to-artifact "$ARTIFACT" --dm-catalog-token "${{ secrets.DATAMINER_DEPLOY_KEY }}")" >> $GITHUB_OUTPUT

      - name: Deploy package from Catalog
        run: dataminer-package-deploy from-volatile --artifact-id "${{ steps.uploadSkyline.outputs.id }}" --dm-system-token "${{ secrets.DATAMINER_DEPLOY_KEY }}"
