name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true

      - name: build documentation
        run: |
          docfx build --warningsAsErrors

      - name: Building
        run: dotnet build

      #- name: publish results
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: Documentation
      #    path: _site/

      #- uses: actions/download-artifact@v4
      #  with:
      #    name: Documentation
      #    path: DummyScript/CompanionFiles/Skyline DataMiner/Webpages/Public/Documentation

  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Job
    needs: build_job
    if: ${{ secrets.DATAMINER_DEPLOY_KEY != '' }}
    steps:
      - uses: actions/checkout@v6

      - name: Install .NET Tools
        run: |
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.DataMinerDeploy

      - name: Upload package to Catalog (Skyline)
        id: uploadSkyline
        run: |
          ARTIFACT=$(find "${{ github.workspace }}/Documentation/bin/Debug" -name "*.dmapp" | head -n 1)
          echo "id=$(dataminer-catalog-upload --path-to-artifact "$ARTIFACT" --dm-catalog-token "${{ secrets.DATAMINER_DEPLOY_KEY }}")" >> $GITHUB_OUTPUT

      - name: Deploy package from Catalog (Skyline)
        run: dataminer-package-deploy from-volatile --artifact-id "${{ steps.uploadSkyline.outputs.id }}" --dm-system-token "${{ secrets.DATAMINER_DEPLOY_KEY }}"
