name: Build and Deploy Documentation

on:
  push:
    branches:
      - AddDocumentationProject
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - AddDocumentationProject
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build Job
    defaults:
      run:
        working-directory: Documentation
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: install DocFX
        run: dotnet tool update -g docfx
        env:
          CI: true

      - name: Build Documentation project
        run: dotnet build

      - name: Identify Static Website Path
        id: identifyPath
        run: |
          DEST=$(jq -r '.build.dest' docfx.json)
          PATH_SITE=$(realpath "$DEST")
          echo "Static site found at: $PATH_SITE"
          echo "PATH_SITE=$PATH_SITE" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.identifyPath.outputs.PATH_SITE }}

  check_secrets:
    name: Check Secrets - DataMiner Deploy Key
    runs-on: ubuntu-latest
    outputs:
      HAS_DATAMINER_DEPLOY_KEY: ${{ steps.check.outputs.DATAMINER_DEPLOY_KEY }}
    steps:
      - run: >
          echo "DATAMINER_DEPLOY_KEY=${{ env.DATAMINER_DEPLOY_KEY != '' }}" >> $GITHUB_OUTPUT
        id: check
        env:
          DATAMINER_DEPLOY_KEY: ${{ secrets.DATAMINER_DEPLOY_KEY }}


  # Deployment job
  deploy_githubpages:
    name: Deploy to GitHub Pages
    environment:
      name: Deploy to GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  deploy_dataminer:
    runs-on: ubuntu-latest
    name: Deploy to DataMiner
    needs: ["build_job", "check_secrets"]
    if: needs.check_secrets.outputs.HAS_DATAMINER_DEPLOY_KEY == 'true'
    defaults:
      run:
        working-directory: Documentation

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: install DocFX
        run: dotnet tool update -g docfx

      - name: Build Documentation project
        run: dotnet build

      - name: Install .NET Tools
        run: |
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.CatalogUpload
          dotnet tool install -g Skyline.DataMiner.CICD.Tools.DataMinerDeploy

      - name: Upload package to Catalog
        id: uploadSkyline
        run: |
          ARTIFACT=$(find bin/Debug -name "*.dmapp" -exec realpath {} \; | head -n 1)
          echo "Artifact found at: $ARTIFACT"
          UPLOAD_OUTPUT=$(dataminer-catalog-upload --path-to-artifact "$ARTIFACT" --dm-catalog-token "${{ secrets.DATAMINER_DEPLOY_KEY }}")
          echo "id=$UPLOAD_OUTPUT" >> $GITHUB_OUTPUT

      - name: Deploy package from Catalog
        run: dataminer-package-deploy from-volatile --artifact-id "${{ steps.uploadSkyline.outputs.id }}" --dm-system-token "${{ secrets.DATAMINER_DEPLOY_KEY }}"
